import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {
    Analytics,
    ProgressBar,
    TailwindIndicator,
    ThemeProvider,
} from '@/components';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <ProgressBar>{children}</ProgressBar>
                    <Analytics />
                    <TailwindIndicator />
                </ThemeProvider>
            </body>
        </html>
    );
}
